[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
board_build.flash_size = 2MB
board_upload.flash_size = 2MB
monitor_speed = 921600
build_flags = 
  -DCORE_DEBUG_LEVEL=1
  -DROBSTRIDE_DEBUG=1
  